#!/usr/bin/env bash
set -e

# Usage:
# SONATYPE_USER=<sonatype user> SONATYPE_PW=<sonatype pw> PGP_PW=<pgp pw> PGP_SECRET=<pgp secret> ./sbtPublish <publish cmd>

if [ ! "$NIGHTLYBUILD" = "yes" ] && [ ! "$RELEASEBUILD" = "yes" ]; then
    echo "Neither NIGHTLYBUILD nor RELEASEBUILD env var set to \"yes\""
    exit 1
fi

# Setup gpg (disabled, we use bouncycastle instead)
# export GPG_TTY="$(tty)"
# echo "$PGP_SECRET" | gpg --batch --import

# run sbt with the supplied arg
SBT="$(cd "$(dirname "${BASH_SOURCE[0]}")" >& /dev/null && pwd)/sbt"
CB_MVN_REPO_URL=https://scala3.westeurope.cloudapp.azure.com/maven2/test-release
"$SBT" 'set every sonatypePublishToBundle := Some("Community Build Repo" at sys.env("CB_MVN_REPO_URL")); scala3-bootstrapped/publish'
